# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Terraform Validate

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Terraform Validate
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.3

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate